apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-web
  namespace: default
  labels:
    app: light-messages-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light-messages-web
  template:
    metadata:
      labels:
        app: light-messages-web
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - light-messages-web
              topologyKey: "topology.kubernetes.io/zone"
      containers:
        - name: backend-web
          image: abdelslam1997/light_messages_backend:latest
          command: ["/bin/sh", "-c", "/start.sh"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: SERVICE_TYPE
              value: "web"
          envFrom:
            - secretRef:
                name: light-messages-secrets
            - secretRef:
                name: django-s3-credentials
            - secretRef:
                name: rds-credentials