apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-web
  namespace: default
  labels:
    app: light-messages-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: light-messages-web
  template:
    metadata:
      labels:
        app: light-messages-web
    spec:
      containers:
        - name: backend-web
          image: abdelslam1997/light_messages_backend:v1.0.25
          command: ["/bin/sh", "-c", "/start.sh"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
              livenessProbe:
                httpGet:
                  path: /api/v1/health   # Define a simple health check endpoint in your app
                  port: 8000
                initialDelaySeconds: 10
                periodSeconds: 15
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: SERVICE_TYPE
              value: "web"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - secretRef:
                name: light-messages-secrets
            - secretRef:
                name: django-s3-credentials
            - secretRef:
                name: rds-credentials