apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-file-server
spec:
  selector:
    matchLabels:
      app: static-file-server
  replicas: 1
  template:
    metadata:
      labels:
        app: static-file-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - name: shared-storage
          mountPath: /usr/share/nginx/html/static
          subPath: static
        - name: shared-storage
          mountPath: /usr/share/nginx/html/media
          subPath: media
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-storage-pvc
      - name: nginx-config
        configMap:
          name: nginx-static-config
---
apiVersion: v1
kind: Service
metadata:
  name: static-file-server
spec:
  selector:
    app: static-file-server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-static-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location /static/ {
            alias /usr/share/nginx/html/static/;
            autoindex off;
        }

        location /media/ {
            alias /usr/share/nginx/html/media/;
            autoindex off;
        }
    }
