---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: light-messages-channels
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:abdelslam1997/light_messages_iac.git
    targetRevision: main
    path: k8s/production/channels
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true