apiVersion: v1
kind: Service
metadata:
  name: channels-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: websocket
      port: 8080
      targetPort: websocket
      protocol: TCP
  selector:
    app: light-messages-channels
