apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-messages-channels
  namespace: default  # Add explicit namespace
  labels:
    app: light-messages-channels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light-messages-channels
  template:
    metadata:
      labels:
        app: light-messages-channels
    spec:
      containers:
        - name: backend-channels
          image: abdelslam1997/light_messages_backend:latest
          command: ["/bin/sh", "-c", "/start.sh"]
          ports:
            - name: websocket
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: SERVICE_TYPE
              value: "channel"
          envFrom:
            - secretRef:
                name: light-messages-secrets
            - secretRef:
                name: django-s3-credentials